# Site settings
title: Vivian Pennel
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A software journeyman blog and website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.vivian-pennel.fr" # the base hostname & protocol for your site
twitter_username: vp3n
github_username:  vp3n
excerpt_separator: <!--more-->
# Build settings
markdown: kramdown

gems:
  - jekyll-feed
